version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/code/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/code/"
    schedule:
      interval: "weekly"
